version: "3.7"

services:
  apinetcore-service:
    build:
      context: .
      dockerfile: ./Dockerfile
  nginx-service:
    image: nginx
    depends_on:
      - apinetcore-service
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
